title: "The Adriatic"
description: "An open-source initiative for tracking global news, conflict, and intelligence"
url: "https://tramci.github.io"
baseurl: "/azt"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/

# Collections
collections:
  posts:
    output: true

# Default settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Categories - UPDATED
categories: [business, politics, culture, opinion]

# Build settings
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
