title: "azt"
description: "An open-source initiative for tracking global news, conflict, and intelligence"
url: "https://tfhoerest.github.io"
baseurl: "/azt"

markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - README.md
